- name: Install Python
  apt: pkg=python,python-setuptools,python-pip,python-dev

- name: Install Python tools
  apt: pkg=python-imaging,python-pycurl

- name: Install build tools
  apt: pkg=build-essential,git

- name: Install Python libs
  apt: pkg=libxml2-dev,libxslt-dev,python-imaging

- name: Install Supervisor
  apt: pkg=supervisor

- name: Install CouchDB
  apt: pkg=couchdb

- name: Install Newebe
  pip: name='git+https://github.com/gelnior/newebe.git#egg=newebe'

- name: Add group Newebe
  group: name=newebe

- name: Add user Newebe
  user: name=newebe shell=/bin/bash groups=newebe

- name: Create Newebe Config folder
  file: path=/usr/local/etc/newebe/ owner=newebe group=newebe state=directory

- name: Create Newebe folder
  file: path=/usr/local/var/newebe/ owner=newebe group=newebe state=directory

- name: Create Newebe log folder
  file: path=/usr/local/var/log/newebe/ owner=newebe group=newebe state=directory

- name: Set Newebe config file
  copy: src=config.yaml dest=/usr/local/etc/newebe/config.yaml owner=newebe group=newebe

- name: Set Supervisor config file
  copy: src=newebe.conf dest=/etc/supervisor/conf.d/newebe.conf

- name: Set Newebe Supervisor config file
  copy: src=supervisor.conf dest=/etc/supervisor/supervisor.conf

- name: Reload Supervisor and start Newebe
  command: /usr/bin/supervisorctl update
